### ISSUE TITLE
vue资料汇总

### ISSUE THREAD

**Issue by dingyiming** [dingyiming/vuejs-start#4]
文档收集截止日期（2015年11月26日周四）
文档&社区
Vue.js官方网站（中文）
Vue论坛
vue-router
组件库

文章
《Vue.js：轻量高效的前端组件化方案》
《Vue.js 和 Webpack》(一)(二)(三)
《尤小右采访》作者的采访有一些设计理念
  腾讯全端 AlloyTeam 团队《mvvm学习&vue实践小结》
  Vue + webpack 项目实践
  Vue.js 源码学习笔记
  Vue教程

项目
《青城主题》
《Cnodejs.org社区webapp》
《vingojw/vue-vueRouter-webpack》
  Bootstrap components built with Vue.js
  A blog based on Github pages by vue.js + webpack
 HackerNews clone with Vue.js
 官方示例
 用Vue实现的拖拽效果
 Chat by Vue + Webpack
 vue-mui
 laracasts/Laravel-and-Vue
 Vue.js + Redux
 Vue.js + Webpack example
 基于Vue、Bootstrap的一套MVVM组件，简单、易用、功能强大
一个php的cms，前端用vuejs

视频
 尤小右分享vuejs 数据驱动的组件化前端开发
 laracasts.com Vuejs1.0教程

技术交流
 Vue的聊天室
 Vuejs官方推特

**Comment by zhaozhe0831** [comment]
有具体链接没？

**Comment by hexuanzhang** [comment]
http://www.jianshu.com/p/afd8e1db7d9b @zhaozhe0831
