### ISSUE TITLE
关于vue更可用的组件化的探索过程（逐步研究，持续跟进）

### ISSUE THREAD

**Issue by dingyiming** [dingyiming/vuejs-start#5]
> 测试项目： https://github.com/dingyiming/vue-es5-template

## 2016.07.28 周四

* 经过本周的持续优化探索，对于vue组件化的初步方案有了更明确的实现解决措施，有利于进一步完善对于组件化的规范的探索

### 阶段1  

- 以页面为组件，直接开发，路由切换，少量跨页面的逻辑，通过vue-router的 $route解决一下下，复用难度大，规范混乱，CSS仅仅使用了简单的 项目-工程师名拼音简称-模块-内容 的命名方式粗暴地进行防止CSS冲突
- html代码块集中，js中状态混杂在一起，无法复用数据逻辑等

### 阶段2

- 考虑所有页面通过组件拼接形成，但数据流以内以内聚为导向，划分了 元件element 、模块 module 、服务 service三层组件，但对于 module与service的界限不明确，对于service所要承担的内容也不明确，逐步探索。。。复用度依然堪忧，并考虑了 使用mixin混合所有页面中需要用到的组件，优先mixin了所有用到的第三方vux库中的组件，看起来还不错

### 阶段3

- 为了能让数据流更加清晰，数据有单独处理的地方，用vue-es5-template参考 vuex文档，进行了初步的学习，搞通了整体数据流的实现方案，对vuex的使用熟悉了，然后引入到项目中去，但发现vuex的引入，让我突然不知道是该让组件内部数据由内部处理，还是如何配合v uex实现更好地统一状态管理，刚开始是打算说 组件内部使用原来的方式内聚进行，但是考虑到在组件内部的状态如果vuex或者其他组件想要去操作就会出现难以进行的局面，顿时卡住了的感觉，进一步考虑如何更好地配合vuex，而不至于有种加了vuex更累赘的感觉

### 阶段4

- 为了让每个组件的状态不仅自己可以用，其他组件需要时候也能直接使用，配合vuex，在所有组件中默认加入了action.js 和state.js ，state用于在当前所需要用到的app中进行注册该组件的状态托管，action在状态托管后的应用中的任意组件中使用mixin将组件的action混入后，便可以直接操作的组件内部的数据状态，很方便，注意的是state在注册的时候遵循约定，用组件名称的小写，以及横杠改为下划线，进行注册，默认在组件内的action都是通过state.组件名小写.具体的数据进行操作的，这是由于通过vuex的模块合并，把每个组件状态汇聚到应用中了，所以多加了一层定位，让数据所在状态更加清晰了。
- 一个基本的组件会是这样：

![image](https://cloud.githubusercontent.com/assets/12537013/17202239/b282aab4-54ca-11e6-9a6b-c55f47a18cb4.png)

![image](https://cloud.githubusercontent.com/assets/12537013/17235256/340efb30-5572-11e6-895c-7482231747bd.png)

**Comment by dingyiming** [comment]
* 高可用的 目标不仅仅是高度可复用，更进一步的是 组件的高度可定制
* 以前端目前来看，所要关注的核心便是 html结构 、对应的数据结构 、以及各种交互

**Comment by dingyiming** [comment]
## 阶段7

*  借鉴京东 athena https://aotu.io/notes/2016/07/19/A-little-exploration-of-front-end-engineering/ 以及前端规范，自己进一步细化前端状态，考虑可复用的前端组件，以及拼装
*  状态由全局统一维护，父子组件数据不耦合。对于组件来说，API来自prop、事件和slot，用好和用对这三者即可。(https://www.talkingcoder.com/article/6310724958473489215)
*  目前我这边的情况，打算直接独立项目来做组件库的事情，并且带有业务特性的服务组件也放在其中,然后组件就是直接一层widget ,一个组件自己结构下的可拼装都放在这个wiget里，实现的服务组件放特定service中

**Comment by dingyiming** [comment]
## H5 CSS reset.css  (参考https://guide.aotu.io/docs/css/reset.html 移动端 )

```
/* 基于 normailze.css 后进行的CSS初始化 */



* {

    -webkit-tap-highlight-color: transparent;

    outline: 0;

    margin: 0;

    padding: 0;

    vertical-align: baseline;

}

body, h1, h2, h3, h4, h5, h6, hr, p, blockquote, dl, dt, dd, ul, ol, li, pre, form, fieldset, legend, button, input, textarea, th, td {

    margin: 0;

    padding: 0;

    vertical-align: baseline;

}

img {

    border: 0 none;

    vertical-align: top;

}

i, em {

    font-style: normal;

}

ol, ul {

    list-style: none;

}

input, select, button, h1, h2, h3, h4, h5, h6 {

    font-size: 100%;

    font-family: inherit;

}

table {

    border-collapse: collapse;

    border-spacing: 0;

}

a {

    text-decoration: none;

    color: #666;

}

body {

    margin: 0 auto;

    min-width: 320px;

    max-width: 640px;

    height: 100%;

    font-size: 15px;

    font-family: Helvetica, STHeiti STXihei, Microsoft JhengHei, Microsoft YaHei, Arial, sans-serif;

    line-height: 1;

    color: #666;

    -webkit-text-size-adjust: 100% !important;

    text-size-adjust: 100% !important;

}

input[type="text"], textarea {

    -webkit-appearance: none;

    -moz-appearance: none;

    appearance: none;

}



button:focus {

    outline-color: #fff;

}
```

**Comment by dingyiming** [comment]
![image](https://cloud.githubusercontent.com/assets/12537013/17328638/5f49c4ba-58f1-11e6-9297-5343f2c53668.png)

**Comment by dingyiming** [comment]
![image](https://cloud.githubusercontent.com/assets/12537013/17328647/68ac4ec4-58f1-11e6-949a-ade054167b84.png)

**Comment by dingyiming** [comment]
![image](https://cloud.githubusercontent.com/assets/12537013/17328708/d0273f3c-58f1-11e6-969b-d8eabdea9b75.png)

**Comment by dingyiming** [comment]
阶段 8 ： 基于远大的生产力工具目标，需要些时间成本，考虑用折中的方案来实现前端定制化，这样，定制化需求，就分成了两部分， 1. 用户可定制 2. 开发高可用 ，优先实践前者，从中再不断提炼复用，逐步成长去实现第二步

*  用户定制：具体方案：
    *  前端每个模块单独打包，上传资源库，注册模块，模块可以单独引用显示，独立运作，完善功能的约定
    *  前期，通过每个模板中将模块组装成页面，配置到项目中去独立使用，逐步提炼模块，完善可复用，页面只有引入模块的操作
    *  前端用动态路由和动态组件匹配出了主页的其他页面，为后面真正自定制奠定基础，

![image](https://cloud.githubusercontent.com/assets/12537013/17329166/fa071cee-58f3-11e6-935c-bd0ea49b83ef.png)

**Comment by dingyiming** [comment]
![image](https://cloud.githubusercontent.com/assets/12537013/17329178/11e22ec6-58f4-11e6-956f-0592ac53aceb.png)

**Comment by dingyiming** [comment]
![image](https://cloud.githubusercontent.com/assets/12537013/17329197/20e2cd72-58f4-11e6-999b-9862c48442cd.png)

**Comment by dingyiming** [comment]
![image](https://cloud.githubusercontent.com/assets/12537013/17329211/3527dea8-58f4-11e6-9301-7805071f9574.png)

**Comment by dingyiming** [comment]
![image](https://cloud.githubusercontent.com/assets/12537013/17329275/8aeb7b6a-58f4-11e6-93d8-a27ee10ba227.png)

**Comment by dingyiming** [comment]
*  项目首页 先发起请求获取首页模块配置，然后首页中模块链接连向其他动态路由，当进入动态路由后，携带动态路由名发起请求，从后端获取配置好的当前页面的模块清单，然后用script的方式组装到页面，也就是说改配置内容，也就改了页面，在后台可以动态修改页面模块清单，实现用户定制需求。

**Comment by dingyiming** [comment]
## 2016.08.03
*  很有借鉴意义的
![image](https://cloud.githubusercontent.com/assets/12537013/17351146/aab67f16-595e-11e6-9652-97b44c71959d.png)

**Comment by dingyiming** [comment]
* 可能我更想 这样做 -  组件 - 模块 - 页面 - 服务 - 应用 
*  其他人的方案 是  组件 - 页面 - 模块 - 项目
*  主要觉着 一个页面只需要去拼接模块就可以，不需要其他操作，页面之间只有路由跳转别无关联，组件具有一定复用度，可以拼上一些数据、交互来实现完整小功能的模块，模块自己封闭，拼接生成页面，可能会多个页面一起去实现一种具体的服务功能，也就是说，组件是可复用的结构性UI内容，然后模块来拼装需要关联的组件，加上样式、交互、数据实现特定的功能，其实这样还是比较合理的，层层规范，不需要加元件层了，组件就是元件一类的内容

**Comment by dingyiming** [comment]
![image](https://cloud.githubusercontent.com/assets/12537013/17351589/92e4d53c-5962-11e6-9077-7a90e126a280.png)

**Comment by dingyiming** [comment]
补充之前刚开始阶段1、2时候的考虑的整体结构图
![h5-saas 4](https://cloud.githubusercontent.com/assets/12537013/17351793/285c503a-5964-11e6-9222-556fe84a09e1.png)

**Comment by dingyiming** [comment]
## 阶段 10 

*  让webpack配置可复用，每个项目中依赖更少的内容，全部由库去统一管理，强化复用
*  用npm scripts 进行

```
  "scripts": {
    "dev": "webpack-dev-server --config ./node_modules/ylc/webpack/dev.js --inline --hot --port 8080",
    "master": "rm -rf dist && webpack --config ./node_modules/ylc/webpack/gitlab.master.js -p"
  },
```

![image](https://cloud.githubusercontent.com/assets/12537013/17357267/94c31216-598e-11e6-98bc-008276bd18ee.png)

*  项目目录逐步减少
![image](https://cloud.githubusercontent.com/assets/12537013/17357371/d4d2e0ac-598e-11e6-92e3-7525e070275e.png)

**Comment by dingyiming** [comment]
![image](https://cloud.githubusercontent.com/assets/12537013/17357489/63affe18-598f-11e6-88b7-d7f6c55454ac.png)

*  目前处在第一期 - 项目由页面配置生成

**Comment by dingyiming** [comment]
*  目前正在建设的方案
![image](https://cloud.githubusercontent.com/assets/12537013/17391003/e9abc294-5a44-11e6-9456-b17691cfc96b.png)

**Comment by dingyiming** [comment]
GraphQL http://taobaofed.org/blog/2015/11/26/graphql-basics-server-implementation/
Falcor :http://netflix.github.io/falcor/
Flux再进化：Introducing Relay and GraphQL译 https://segmentfault.com/a/1190000002570887

**Comment by dingyiming** [comment]
*  突然发现，目前最好不要直接在html中就操作vuex 的 action ,可以通过本地methods来转一下，因为目前还没确定其他本地状态如何进行有效维护，所以先用这个方法来理顺再进一步，actions目前的作用也仅仅是具体的ajax操作数据，但为啥操作，什么时候操作都由本地method来控制，比较不错

**Comment by dingyiming** [comment]
*  组件 有几种， 数据、本地状态（交互）、UI组件、UI元件，需要统筹规划一下，欠缺规范，生产力较低下
*  最好尽快改为.vue的组织方式，目前文件目录已经比较多，零碎片段居多’

**Comment by dingyiming** [comment]
*  http://mobile.ant.design/ 接下来值得好好模仿的H5规范

**Comment by dingyiming** [comment]
![image](https://cloud.githubusercontent.com/assets/12537013/17521232/33fd5c56-5e85-11e6-9b48-a0c4afeca9e8.png)

**Comment by dingyiming** [comment]
对于组件的认知仍然需要进一步深化，逐步形成各种状态的组件，可以有机组合，目前以一个项目为目标，完善前端基础结构；

！！！一定要使用flex布局所有H5页面

**Comment by dingyiming** [comment]
## 2016 . 08.23

经过一段时间项目的探索，逐步明白要怎么去做，虽然我们是要面对一个系统，但是每个项目依然可以是独立的，只是模板是共享的，组件库是共享的，技术方案是一致的，在不断摸索中让技术方案不断成长，但对于项目所用技术方案必须比技术探索滞后一个阶段，才能稳固保障项目，同时再探索项目中逐步调整，这才是有助于整体发展的，之前在项目中调整了好几次结构，这是不可取的，谨此教训。

*  组件化方针 上，使用 page /  subpage / components  的方法，比较合理 ，page和subpage根据需要进行调整
![image](https://cloud.githubusercontent.com/assets/12537013/17877871/15431ed8-6919-11e6-8587-0f80bea777a5.png)

*  组件层级就分 两层即可 

![image](https://cloud.githubusercontent.com/assets/12537013/17877912/849a1f16-6919-11e6-8913-1c9cda8c506c.png)

*  数据通信上 ， 应用层状态才放vuex/redux  ，然后一些接口的对接目前放在了单独的api中，基本就是用于发个ajax,回调一下即可，具体数据逻辑放到页面中进行

![image](https://cloud.githubusercontent.com/assets/12537013/17877915/913103d4-6919-11e6-9188-22c00ac9fbdc.png)

**Comment by dingyiming** [comment]
什么样的项目适合SAAS ,需要进一步明确，先要开个表单把SAAS功能列出来，然后用表单的是否提供给客户去填写所需要的功能选择

**Comment by dingyiming** [comment]
## 近期升Vue2 进一步强化前端技术熟练度 2016.09.05

**Comment by 7greenfrog7** [comment]
你好，看了你的vue+sass项目之路，我有一个问题想要请教你：
配置前端页面的后台项目与前端页面的渲染项目，请问你是放在同一个app去做的，还是怎么做的？
我的理解是，页面的搭建是在管理后台完成（搭建页面的vue组件都在后台vue-app中），但对于用户来说，这些搭建的HTML页面不应该在后台的vue-app中去渲染的，所以这就形成了矛盾。
而且生成的HTML页面，为了考虑SEO，应当使用vue的服务端渲染，这样就更不可能让sass前端页面项目和管理后台的搭建页面项目在一个app中。
请问你对于这个问题有什么想法吗？
